export const TYPES = {
  RedisClient: Symbol.for("RedisClient"),
  KeyAttributesCache: Symbol.for("KeyAttributesCache"),
  ProductService: Symbol.for("ProductService"),
  FilterService: Symbol.for("FilterService"),
  CategoryService: Symbol.for("CategoryService"),
  RequestScopedStorage: Symbol.for("RequestScopedStorage"),
  FilterCacheRepository: Symbol.for("FilterCacheRepository"),
  FilterRepository: Symbol.for("FilterRepository"),
  FilterCache: Symbol.for("FilterCache"),
  CategoryRepository: Symbol.for("CategoryRepository"),
  RedisThirdParty: Symbol.for("RedisThirdParty"),
  GlobalErrorHandler: Symbol.for("GlobalErrorHandler"),
  ValidateAndSanitizeQueryFilters: Symbol.for(
    "ValidateAndSanitizeQueryFilters"
  ),
  ValidateParam: Symbol.for("ValidateParam"),
  ValidateCreateCategory: Symbol.for("ValidateCreateCategory"),
  DiskStorageStrategy: Symbol.for("DiskStorageStrategy"),
  MemoryStorageStrategy: Symbol.for("MemoryStorageStrategy"),
  FileUploadMiddlewareFactory: Symbol.for("FileUploadMiddlewareFactory"),
  ProductWriteRepository: Symbol.for("ProductWriteRepository"),
  ProductReadRepository: Symbol.for("ProductReadRepository"),
  ProductCreateUseCase: Symbol.for("ProductCreateUseCase"),
  InventoryRepositoryWrite: Symbol.for("InventoryRepositoryWrite"),
  ErrorConverter: Symbol.for("ErrorConverter"),
  RequestContextBuilder: Symbol.for("RequestContextBuilder"),
  ErrorLogger: Symbol.for("ErrorLogger"),
  Logger: Symbol.for("Logger"),
  LoggingMiddleware: Symbol.for("LoggingMiddleware"),
  InventoryCreateUseCase: Symbol.for("InventoryCreateUseCase"),
  ProductReadUseCase: Symbol.for("ProductReadUseCase"),
  ProductUpdateUseCase: Symbol.for("ProductUpdateUseCase"),
  InventoryUpdateUseCase: Symbol.for("InventoryUpdateUseCase"),
  InventoryRepositoryRead: Symbol.for("InventoryRepositoryRead"),
  InventoryReadUseCase: Symbol.for("InventoryReadUseCase"),
  InventoryRepositoryUpdate: Symbol.for("InventoryRepositoryUpdate"),
  InventoryRepositoryDelete:Symbol.for("InventoryRepositoryDelete"),
  InventoryDeleteUseCase: Symbol.for("InventoryDeleteUseCase")
};
